# Generated by Django 3.1.7 on 2021-03-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(max_length=256, null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': ('Contact',),
                'verbose_name_plural': ('Contact',),
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscription',
            },
        ),
    ]
