# Generated by Django 3.1.7 on 2021-03-03 03:50

from django.db import migrations, models
import painless.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210228_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=256, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to=painless.upload_to.post_directory_path, verbose_name='Thumbnail'),
        ),
    ]
