# Generated by Django 3.1.7 on 2021-02-28 23:54

import django.core.validators
from django.db import migrations, models
import painless.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210228_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=painless.upload_to.product_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Image'),
        ),
    ]
