# Generated by Django 3.1.7 on 2021-03-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210228_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_for_get_price',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Call For Get Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available'), ('S', 'Soon')], default='A', max_length=1, null=True, verbose_name='Availability'),
        ),
    ]
