# Generated by Django 3.1.7 on 2021-03-03 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210303_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Image'),
        ),
    ]
